import {FaLocationDot as icon } from 'react-icons/fa6';

export default {
  name: "address",
  title: "Addresses",
  type: "document",
  icon,
  fields: [
    {
      name: 'name',
      title: 'Name',
      type: 'string',
      description:  'Name for location'
    },
    {
      name: 'address',
      title: 'Street Address',
      type: 'string',
      description:  'Street address of location'
    },
    {
      name: 'city',
      title: 'City',
      type: 'string',
      description:  'City of location'
    },
    {
      name: 'state',
      title: 'State',
      type: 'string',
      description:  'State of location',
      initialValue: 'us-south',
      options: {
        list: [
          { title: 'Alabama', value: 'AL' },
          { title: 'Alaska', value: 'AK' },
          { title: 'American Samoa', value: 'AS' },
          { title: 'Arizona', value: 'AZ' },
          { title: 'Arkansas', value: 'AR' },
          { title: 'California', value: 'CA' },
          { title: 'Colorado', value: 'CO' },
          { title: 'Connecticut', value: 'CT' },
          { title: 'Delaware', value: 'DE' },
          { title: 'District of Columbia', value: 'DC' },
          { title: 'Florida', value: 'FL' },
          { title: 'Georgia', value: 'GA' },
          { title: 'Guam', value: 'GU' },
          { title: 'Hawaii', value: 'HI' },
          { title: 'Idaho', value: 'ID' },
          { title: 'Illinois', value: 'IL' },
          { title: 'Indiana', value: 'IN' },
          { title: 'Iowa', value: 'IA' },
          { title: 'Kansas', value: 'KS' },
          { title: 'Kentucky', value: 'KY' },
          { title: 'Louisiana', value: 'LA' },
          { title: 'Maine', value: 'ME' },
          { title: 'Maryland', value: 'MD' },
          { title: 'Massachusetts', value: 'MA' },
          { title: 'Michigan', value: 'MI' },
          { title: 'Minnesota', value: 'MN' },
          { title: 'Mississippi', value: 'MS' },
          { title: 'Missouri', value: 'MO' },
          { title: 'Montana', value: 'MT' },
          { title: 'Nebraska', value: 'NE' },
          { title: 'Nevada', value: 'NV' },
          { title: 'New Hampshire', value: 'NH' },
          { title: 'New Jersey', value: 'NJ' },
          { title: 'New Mexico', value: 'NM' },
          { title: 'New York', value: 'NY' },
          { title: 'North Carolina', value: 'NC' },
          { title: 'North Dakota', value: 'ND' },
          { title: 'Northern Mariana Islands', value: 'MP' },
          { title: 'Ohio', value: 'OH' },
          { title: 'Oklahoma', value: 'OK' },
          { title: 'Oregon', value: 'OR' },
          { title: 'Pennsylvania', value: 'PA' },
          { title: 'Puerto Rico', value: 'PR' },
          { title: 'Rhode Island', value: 'RI' },
          { title: 'South Carolina', value: 'SC' },
          { title: 'South Dakota', value: 'SD' },
          { title: 'Tennessee', value: 'TN' },
          { title: 'Texas', value: 'TX' },
          { title: 'Trust Territories', value: 'TT' },
          { title: 'Utah', value: 'UT' },
          { title: 'Vermont', value: 'VT' },
          { title: 'Virgin Islands', value: 'VI' },
          { title: 'Virginia', value: 'VA' },
          { title: 'Washington', value: 'WA' },
          { title: 'West Virginia', value: 'WV' },
          { title: 'Wisconsin', value: 'WI' },
          { title: 'Wyoming', value: 'WY' },
        ],
      }
    },
    {
      name: 'zip',
      title: 'Zipcode',
      type: 'string',
      description:  'Zipcode of location'
    },
    {
      name: 'longitude',
      title: 'Longitude',
      type: 'string',
      description:  'longitude of location'
    },
    {
      name: 'latitude',
      title: 'Latitude',
      type: 'string',
      description:  'latitude of location'
    },
  ],
}